### ISSUE TITLE
Issue with bond_price when settlement date is coupon paying day

### ISSUE THREAD

**Issue by ionmihai** [jrvarma/bond_pricing#1]
Disregard my previous edit. It looks like the error is happening even when the yld is specified. I think the issue is that bound_coupon_periods miscalculates the number of coupons left, when the settlement date is a coupon-paying day. Sorry for the confusion.

**Comment by jrvarma** [comment]
Please elaborate on the error. 
The price (137.9748)  that I get for 
```
bond.price("2021-01-01", "2031-01-01", 5e-2, 2, 1e-2)
```
matches what I get from Microsoft Excel.

**Comment by ionmihai** [comment]
That is odd. I do not get the same price. The exact command I use is 

bond_pricing.simple_bonds.bond_price(settle = "2021-01-01", mat = "2031-01-01", yld = 1e-2, freq = 2, cpn = 5e-2)

This gives me a price of 136.164.

**Comment by jrvarma** [comment]
I am sorry. I was testing my [`R` code](https://github.com/jrvarma/jrvFinance) instead of my `Python` code. My bad. 

Let me see what went wrong when I translated from `R` to `Python`.

**Comment by ionmihai** [comment]
Thank you. If this helps, I noticed that " bound_coupon_periods" reports the wrong number of coupons left when the settlement date is a coupon day.

**Comment by jrvarma** [comment]
Thanks a lot. Have fixed the bug and pushed to `github` and `PyPi` as well as version 0.6.3. Please upgrade and see whether this works. Ran some tests, but would appreciate your test results as well.

Thanks for pointing this out. I was incrementing the number of coupons only when not on a coupon date, but the incrementing is always required.

**Comment by ionmihai** [comment]
Thank you for the quick fix. I ran some tests and everything comes out ok except for one thing: prices under 'actual/actual' are slightly different from Excel results. e.g.

bond_price_breakup(settle = '2016-06-30', mat = '2017-01-01', yld = 0.08, 
                       freq = 2, cpn = 0.06, face = 100, daycount = 'actual/actual')

returns a 99.0275198 clean price, while Excel returns  99.0329583.

All other day counts are ok.

**Comment by jrvarma** [comment]
The actual/actual and other daycounts are coming from <https://github.com/miradulo/isda_daycounters> which claims to follow the ISDA definitions. There are [some reports](https://www.mrexcel.com/board/threads/excel-and-day-count-convention-for-actual-actual.239936/) on the web that Excel does not follow ISDA definitions or any other popular standard definition for actual/actual. If there is an error in <https://github.com/miradulo/isda_daycounters> we can raise an issue there. Do you have access to a Bloomberg terminal or something else that could indicate which number is right?
