### ISSUE TITLE
have you thought of making a project into package? 

### ISSUE THREAD

**Issue by epogrebnyak** [jrvarma/bond_pricing#4]
Thank you for the work in code and docs? Do you need turining your project into pip install something?

**Comment by jrvarma** [comment]
It has been on PyPi for quite some time. 

`pip install bond_pricing`

I will mention this in the readme also.

**Comment by epogrebnyak** [comment]
> It has been on PyPi for quite some time. 
> 
> `pip install bond_pricing`
> 
> I will mention this in the readme also.

Great, thanks, some  follow up thoughts: 


You can also do pip install bond_pricing[scipy] if you consider scipy an optional dependency. Somewhat cleaner than env var. Needs tweaking your setup py though. 


Also a link from docs to GitHub could be great, otherwise it is pure chance some notices git clone and understands where a package lives actually.

**Comment by jrvarma** [comment]
> You can also do pip install bond_pricing[scipy] if you consider scipy an optional dependency. Somewhat cleaner than env var. Needs tweaking your setup py though.

It is not really optional as dropping scipy degrades the package quite significantly. The no-scipy hack is intended only for environments like Windows or Android (Termux) where users have at times struggled to install scipy.

> Also a link from docs to GitHub could be great, otherwise it is pure chance some notices git clone and understands where a package lives actually.

Done

**Comment by epogrebnyak** [comment]
> It is not really optional as dropping scipy degrades the package quite significantly. The no-scipy hack is intended only for environments like Windows or Android (Termux) where users have at times struggled to install scipy.

Scipy on Android shoudl really be a challenge!
