### ISSUE TITLE
Difference from expected yield for bonds with clean_price equal to face_value near maturity

### ISSUE THREAD

**Issue by alonwengierko** [jrvarma/bond_pricing#5]
I am testing bond_yield method using clean price equal to face value (100), so I expect that yield to maturity would be equal to the coupon rate independently of the settle date. However, I see that as the valuation date approach maturity. I see that yield to maturity is smaller than expected.

For example, the following code, computes the yield to maturity for a bond with semiannual coupons. Coupon rate is 9.25%. So if clean price is equal to face value. I would expect that bond_yield method, returns ytm equal to 9.25% independent of the settle. But I see that values differ from expected values, and they differ more as valuation date approach maturity.

```
from bond_pricing import bond_yield

ytm_values = bond_yield(redeem=100,settle=["2012-03-01","2014-03-01","2016-03-01","2018-03-01"], mat="2018-03-27", cpn=0.0925, price=100, freq=2, comp_freq=2, face=100)

print("Yield to maturity:")
for ytm in ytm_values:
    print(round(ytm * 100, 2), "%")
```

The result that I get is:
```
Yield to maturity:
9.25 %
9.25 %
9.24 %
9.07 %
```
It is possible to see that yield to maturity values reduces as we approach maturity. For settle = "2018-03-01", approximately 26 days to maturity, the yield to maturity estimation is 9.07% instead of 9.25%.

**Comment by jrvarma** [comment]
This is due to accrued interest. If you calculate at coupon dates where there is no accrued interest, the yield is exactly 9.25%
```
print(100*bond_yield(
    redeem=100,
    settle=["2012-03-27", "2014-03-27", "2016-03-27", "2017-09-27"],
    mat="2018-03-27",
    cpn=0.0925, price=100, freq=2, comp_freq=2, face=100))
```
Accrued interest complicates matters because the accrued interest is received on settlement date without discounting. To compensate for this, the clean price has to drop below par.
